env:
  browser: true
  es2021: true
extends:
  - airbnb-base/legacy
  - plugin:@typescript-eslint/recommended
  # - some-other-config-you-use
  # - prettier
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
root: true
rules: { 
  quotes: ["error","double"]
  }
